repos:
  - repo: local
    hooks:
    -   id: black
        name: black
        stages: [commit]
        language: system
        entry: black
        types: [python]

    -   id: isort
        name: isort
        stages: [commit]
        language: system
        entry: isort
        types: [python]
        args: ["--profile", "black"]

    -   id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]
        require_serial: true
        args: ['--max-line-length=120', "--ignore=E203,W503,E722", '--per-file-ignores=*/__init__.py: F401']

exclude: 'README.md'