name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.12
      - name: Black, flake8 & isort
        run: |
          pip install black==24.4.2 isort==5.13.2 flake8==7.0.0
          black --check mrs_utils tests
          flake8 --verbose mrs_utils tests
          isort . --check-only --verbose
      - name: Run tests
        run: |
          pip install .[tests]
          pytest